### ISSUE TITLE
Translate the Syntax Reference Page to Spanish

### ISSUE THREAD

**Issue by ByFernanz** [rudism/ficdown#13]
Best regards.

I share a Spanish translation that I made from the Ficdown reference page.

[https://byfernanz.github.io/textalab/manuales/manual-de-ficdown.html](https://byfernanz.github.io/textalab/manuales/manual-de-ficdown.html)

**Comment by rudism** [comment]
This is awesome! I added a link to this from the reference on ficdown.com (and added links to your other tools to a new section on the "Write" page).
