### ISSUE TITLE
Generated epub not valid

### ISSUE THREAD

**Issue by janbru** [rudism/Ficdown#4]
The generated epub works fine with my actual e-reader and with Sigil. But Google Play Books says it cannot import it and refers to http://validator.idpf.org/
And indeed, this validator says the epub has errors.

**Comment by rudism** [comment]
I know this has been open a while, but I finally got around to looking into the validation errors. I believe I have successfully corrected everything. The book now validates at the idpf link and I was able to import a ficdown-generated epub into Google Play Books. The website ficdown.com has been updated to the latest binary with these changes.
